# Generated by Django 4.0.2 on 2022-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(default='static/carousel (1).jpg', upload_to='static'),
        ),
    ]
